/*
Copyright 2019 2019 Bruce Ma

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	resourcev1 "github.com/mars1024/kube-ipam/pkg/apis/resource/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeUsingIPs implements UsingIPInterface
type FakeUsingIPs struct {
	Fake *FakeResourceV1
}

var usingipsResource = schema.GroupVersionResource{Group: "resource.k8s.io", Version: "v1", Resource: "usingips"}

var usingipsKind = schema.GroupVersionKind{Group: "resource.k8s.io", Version: "v1", Kind: "UsingIP"}

// Get takes name of the usingIP, and returns the corresponding usingIP object, and an error if there is any.
func (c *FakeUsingIPs) Get(name string, options v1.GetOptions) (result *resourcev1.UsingIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(usingipsResource, name), &resourcev1.UsingIP{})
	if obj == nil {
		return nil, err
	}
	return obj.(*resourcev1.UsingIP), err
}

// List takes label and field selectors, and returns the list of UsingIPs that match those selectors.
func (c *FakeUsingIPs) List(opts v1.ListOptions) (result *resourcev1.UsingIPList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(usingipsResource, usingipsKind, opts), &resourcev1.UsingIPList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &resourcev1.UsingIPList{ListMeta: obj.(*resourcev1.UsingIPList).ListMeta}
	for _, item := range obj.(*resourcev1.UsingIPList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested usingIPs.
func (c *FakeUsingIPs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(usingipsResource, opts))
}

// Create takes the representation of a usingIP and creates it.  Returns the server's representation of the usingIP, and an error, if there is any.
func (c *FakeUsingIPs) Create(usingIP *resourcev1.UsingIP) (result *resourcev1.UsingIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(usingipsResource, usingIP), &resourcev1.UsingIP{})
	if obj == nil {
		return nil, err
	}
	return obj.(*resourcev1.UsingIP), err
}

// Update takes the representation of a usingIP and updates it. Returns the server's representation of the usingIP, and an error, if there is any.
func (c *FakeUsingIPs) Update(usingIP *resourcev1.UsingIP) (result *resourcev1.UsingIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(usingipsResource, usingIP), &resourcev1.UsingIP{})
	if obj == nil {
		return nil, err
	}
	return obj.(*resourcev1.UsingIP), err
}

// Delete takes name of the usingIP and deletes it. Returns an error if one occurs.
func (c *FakeUsingIPs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(usingipsResource, name), &resourcev1.UsingIP{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUsingIPs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(usingipsResource, listOptions)

	_, err := c.Fake.Invokes(action, &resourcev1.UsingIPList{})
	return err
}

// Patch applies the patch and returns the patched usingIP.
func (c *FakeUsingIPs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *resourcev1.UsingIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(usingipsResource, name, data, subresources...), &resourcev1.UsingIP{})
	if obj == nil {
		return nil, err
	}
	return obj.(*resourcev1.UsingIP), err
}
