/*
Copyright 2019 2019 Bruce Ma

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	resourcev1 "github.com/mars1024/kube-ipam/pkg/apis/resource/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLastReservedIPs implements LastReservedIPInterface
type FakeLastReservedIPs struct {
	Fake *FakeResourceV1
}

var lastreservedipsResource = schema.GroupVersionResource{Group: "resource.k8s.io", Version: "v1", Resource: "lastreservedips"}

var lastreservedipsKind = schema.GroupVersionKind{Group: "resource.k8s.io", Version: "v1", Kind: "LastReservedIP"}

// Get takes name of the lastReservedIP, and returns the corresponding lastReservedIP object, and an error if there is any.
func (c *FakeLastReservedIPs) Get(name string, options v1.GetOptions) (result *resourcev1.LastReservedIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(lastreservedipsResource, name), &resourcev1.LastReservedIP{})
	if obj == nil {
		return nil, err
	}
	return obj.(*resourcev1.LastReservedIP), err
}

// List takes label and field selectors, and returns the list of LastReservedIPs that match those selectors.
func (c *FakeLastReservedIPs) List(opts v1.ListOptions) (result *resourcev1.LastReservedIPList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(lastreservedipsResource, lastreservedipsKind, opts), &resourcev1.LastReservedIPList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &resourcev1.LastReservedIPList{ListMeta: obj.(*resourcev1.LastReservedIPList).ListMeta}
	for _, item := range obj.(*resourcev1.LastReservedIPList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested lastReservedIPs.
func (c *FakeLastReservedIPs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(lastreservedipsResource, opts))
}

// Create takes the representation of a lastReservedIP and creates it.  Returns the server's representation of the lastReservedIP, and an error, if there is any.
func (c *FakeLastReservedIPs) Create(lastReservedIP *resourcev1.LastReservedIP) (result *resourcev1.LastReservedIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(lastreservedipsResource, lastReservedIP), &resourcev1.LastReservedIP{})
	if obj == nil {
		return nil, err
	}
	return obj.(*resourcev1.LastReservedIP), err
}

// Update takes the representation of a lastReservedIP and updates it. Returns the server's representation of the lastReservedIP, and an error, if there is any.
func (c *FakeLastReservedIPs) Update(lastReservedIP *resourcev1.LastReservedIP) (result *resourcev1.LastReservedIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(lastreservedipsResource, lastReservedIP), &resourcev1.LastReservedIP{})
	if obj == nil {
		return nil, err
	}
	return obj.(*resourcev1.LastReservedIP), err
}

// Delete takes name of the lastReservedIP and deletes it. Returns an error if one occurs.
func (c *FakeLastReservedIPs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(lastreservedipsResource, name), &resourcev1.LastReservedIP{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLastReservedIPs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(lastreservedipsResource, listOptions)

	_, err := c.Fake.Invokes(action, &resourcev1.LastReservedIPList{})
	return err
}

// Patch applies the patch and returns the patched lastReservedIP.
func (c *FakeLastReservedIPs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *resourcev1.LastReservedIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(lastreservedipsResource, name, data, subresources...), &resourcev1.LastReservedIP{})
	if obj == nil {
		return nil, err
	}
	return obj.(*resourcev1.LastReservedIP), err
}
