/*
Copyright 2019 2019 Bruce Ma

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/mars1024/kube-ipam/pkg/apis/resource/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LastReservedIPLister helps list LastReservedIPs.
type LastReservedIPLister interface {
	// List lists all LastReservedIPs in the indexer.
	List(selector labels.Selector) (ret []*v1.LastReservedIP, err error)
	// Get retrieves the LastReservedIP from the index for a given name.
	Get(name string) (*v1.LastReservedIP, error)
	LastReservedIPListerExpansion
}

// lastReservedIPLister implements the LastReservedIPLister interface.
type lastReservedIPLister struct {
	indexer cache.Indexer
}

// NewLastReservedIPLister returns a new LastReservedIPLister.
func NewLastReservedIPLister(indexer cache.Indexer) LastReservedIPLister {
	return &lastReservedIPLister{indexer: indexer}
}

// List lists all LastReservedIPs in the indexer.
func (s *lastReservedIPLister) List(selector labels.Selector) (ret []*v1.LastReservedIP, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.LastReservedIP))
	})
	return ret, err
}

// Get retrieves the LastReservedIP from the index for a given name.
func (s *lastReservedIPLister) Get(name string) (*v1.LastReservedIP, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("lastreservedip"), name)
	}
	return obj.(*v1.LastReservedIP), nil
}
