/*
Copyright 2019 2019 Bruce Ma

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/mars1024/kube-ipam/pkg/apis/resource/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// UsingIPLister helps list UsingIPs.
type UsingIPLister interface {
	// List lists all UsingIPs in the indexer.
	List(selector labels.Selector) (ret []*v1.UsingIP, err error)
	// Get retrieves the UsingIP from the index for a given name.
	Get(name string) (*v1.UsingIP, error)
	UsingIPListerExpansion
}

// usingIPLister implements the UsingIPLister interface.
type usingIPLister struct {
	indexer cache.Indexer
}

// NewUsingIPLister returns a new UsingIPLister.
func NewUsingIPLister(indexer cache.Indexer) UsingIPLister {
	return &usingIPLister{indexer: indexer}
}

// List lists all UsingIPs in the indexer.
func (s *usingIPLister) List(selector labels.Selector) (ret []*v1.UsingIP, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.UsingIP))
	})
	return ret, err
}

// Get retrieves the UsingIP from the index for a given name.
func (s *usingIPLister) Get(name string) (*v1.UsingIP, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("usingip"), name)
	}
	return obj.(*v1.UsingIP), nil
}
